wscript.echo "<rss>"
wscript.echo "<channel>"
wscript.echo "<title>Sample VBScript Channel</title>"
wscript.echo "<link>https://test.com</link>"
wscript.echo "<description>Sample VBScript Channel</description>"
wscript.echo "<item>"
wscript.echo "    <title>Item Title 1</title>"
wscript.echo "    <link>https://test.com/item1.html</link>"
wscript.echo "    <description>Item Description 1</description>"
wscript.echo "</item>"
wscript.echo "<item>"
wscript.echo "    <title>Item Title 2</title>"
wscript.echo "    <link>https://test.com/item2.html</link>"
wscript.echo "    <description>Item Description 2</description>"
wscript.echo "</item>"
wscript.echo "<item>"
wscript.echo "    <title>Item Title 3</title>"
wscript.echo "    <link>https://test.com/item3.html</link>"
wscript.echo "    <description>Item Description 3</description>"
wscript.echo "</item>"
wscript.echo "</channel>"
wscript.echo "</rss>"
