""" This is a sample Awasu channel plugin written in Python.

It accepts parameters passed in by Awasu, and generates an RSS feed based on that.
"""

#  COPYRIGHT:   (c) Awasu Pty. Ltd. 2002 (all rights reserved).
#               Unauthorized use of this code is prohibited.
#
#  LICENSE:     This software is provided 'as-is', without any express
#               or implied warranty.
#
#               In no event will the author be held liable for any damages
#               arising from the use of this software.
#
#               Permission is granted to anyone to use this software
#               for any non-commercial purpose and to alter it and
#               redistribute it freely, subject to the following restrictions:
#
#               - The origin of this software must not be misrepresented;
#                 you must not claim that you wrote the original software.
#                 If you use this software, an acknowledgement is requested
#                 but not required.
#
#               - Altered source versions must be plainly marked as such,
#                 and must not be misrepresented as being the original software.
#                 Altered source is encouraged to be submitted back to
#                 the original author so it can be shared with the community.
#                 Please share your changes.
#
#               - This notice may not be removed or altered from any
#                 source distribution.

import sys
import configparser

# ---------------------------------------------------------------------

# get our channel parameters
parser = configparser.ConfigParser()
parser.read( sys.argv[1] )
home_url = parser.get( "ChannelParameters", "HomeUrl", fallback="" )
n_items = int( parser.get( "ChannelParameters", "nItems", fallback=0 ) )

# generate the RSS feed
print( "<rss>" )
print( "<channel>" )
print()
print( "<title>Sample Python Channel 2</title>" )
print( "<link>{}</link>".format( home_url ) )
print( "<description>This is a demo RSS feed generated by the sample Python channel plugin.</description>" )
print()
for i in range( 1, n_items+1 ):
    print( "<item>" )
    print( "    <title>Item {}</title>".format( i ) )
    print( "    <link>{}/item-{}.html</link>".format( home_url, i ) )
    print( "    <description>This is the description for item {}.</description>".format( i ) )
    print( "</item>" )
    print()
print( "</channel>" )
print( "</rss>" )
